version = 0.1

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "openc-lifs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yyyyizs5r6ne"
s3_prefix = "openc-lifs"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
parameter_overrides = "Environment=\"PRODUCTION\""
image_repositories = []
